config/routes.rb
Rails.application.routes.draw do
  resources :apps

end

app/models/app.rb
class App < ActiveRecord::Base
  
  mount_uploader :icon, ImageUploader	

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_user
		redirect_to '/login' unless current_user
	end

end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:name,:publisher, :description, :platform, :availableTo, :availableThrough, :icon)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to '/'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		if @user.save
			@user = User.new(user_params)
			session[:user_id] = @user.id
			redirect_to '/'
		else
			redirect_to '/signup'
		end
	end

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apps/_adminlogin.html.erb
<div id="adminmodal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
    		<h4 class="modal-title"> Login </h4>
  		</div>
			<div class="modal-body">
 				<p>Input Form Field Here</p>
			</div>
  		<div class="modal-footer">
				<button type="button" class="btn-btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/apps/_applicationlist.html.erb
<% x = 0 %>
<% @apps.each do |app| %>
      <tr class='app' id='app-id-<%= x %>'>
        <td><%= link_to image_tag(app.icon_url(:thumb).to_s), app %></td>
	<td><h2><%= link_to app.name, app, class: "anchorStyle" %></h2>
        <div class="my-overflow"><%= app.description %></div>
        <span class='lead'>Platform(s): <%= app.platform %></span></td>
        <td class='aTo'><%= app.availableTo %></td>
        <td class='aThrough'><%= app.availableThrough %></td>
	<td class='admin'><%= link_to 'Show', app %></td>
        <td class='admin'><%= link_to 'Edit', edit_app_path(app) %></td>
        <td class='admin'><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% x += 1 %>
<% end %>

app/views/apps/_form.html.erb
<%= form_for @app, :html => { :multipart => true } do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class='container'>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :platform %><br>
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :availableTo %><br>
    <%= f.text_field :availableTo %>
  </div>
  <div class="field">
    <%= f.label :availableThrough %><br>
    <%= f.text_field :availableThrough %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.file_field :icon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class='row'>
	<div class='myadminbutton'>
		<button class="btn btn-default" data-toggle="modal" data-target="#adminmodal" title="Login">
			<span class="glyphicon glyphicon-user"> Login </span>
		</button>
	</div>
</div>
<%= render 'adminlogin' %>
<div class="jumbotron text-center"><h1>Weber State Software</h1></div>
<table class='table table-hover table-striped'>
  <thead>
    <tr>
      <th></th>
      <th>Description</th>
      <th>Available To</th>
      <th>Available Through</th>	
      <th colspan="2" class='admin'></th>
    </tr>
  </thead>
  <tbody>
    <%= render 'applicationlist' %>
 </tbody>

</table>

<div class='col-md-12'>
  <div class='col-md-3'>
  <ul class="pager">
    <li id="prev" class="previous"><a href="#">Previous</a></li>
  </ul>
  </div>
  <div class='col-md-6 text-center'>
  <% x = 1 %>
  <% y = 1 %>
  <ul class="pagination">
    <% until x > (@apps.count) do %>
      <li id='page-<%= y %>' data-page-number=<%= y %>><a href='#'><%= y %></a></li>
    <!-- Hard coded number of apps per page -->
    <% x += 3 %>
    <% y += 1 %>
    <% end %>
  </ul>
  </div>
  <div class='col-md-3'>
  <ul class="pager">
    <li id="next" class="next"><a href="#">Next</a></li>
  </ul>
  </div>
</div>

</div>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<div class='container'>
  <p id="notice"><%= notice %></p>
  <div class='row well'>
    <div class='col-md-2'></div>
      <div class='col-md-2'>
	<p>
	  <%= image_tag(@app.icon_url(:thumb).to_s, :class => 'vcenter') %>
	</p>
      </div>
    <div class='col-md-6'>
      <p>
        <h1><%= @app.name %></h1>
      </p>
      <p>
        <%= @app.description %>
     </p>

	<p>
	  <h3>Platform: <%= @app.platform %></h3>
	</p>

	<p>
	  <h4>Available to:</h4> <%= @app.availableTo %>
	</p>

	<p>
	  <h4>Available through: </h4>
          <%= @app.availableThrough %>
	</p>
	</div>
      </div>
</div>
<div class="col-md-2"></div>
<div class='row well col-md-12 text-center'>
  <%= link_to 'Edit', edit_app_path(@app) %> | 
  <%= link_to 'Back', apps_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoftwareCatalog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>